config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
    	resources :reports
    end
  end

  get 'home/index'
  resources :reports

  devise_for :users

  root 'home#index'

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user

  def top_adwords_number
  	self.top_adwords_url.count
  end

  def right_adwords_number
  	self.right_adwords_url.count
  end

  def total_adwords_number
  	self.top_adwords_number + self.right_adwords_number
  end

  def non_adwords_number
  	self.non_adwords_url.count
  end

  def total_links
  	self.top_adwords_url.count + self.right_adwords_url.count + self.non_adwords_url.count
  end

  def get_page_cache
  	PGconn.unescape_bytea(self.page_cache)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reports
end

app/controllers/api/v1/reports_controller.rb
require 'nokogiri'
require 'open-uri'

class Api::V1::ReportsController < ApplicationController
  def index
  	@reports = current_user.reports
  	if !params[:adword_present].nil?
  		byebug
  		@reports = @reports.where("'#{params[:adword_present]}' ILIKE ANY (top_adwords_url) OR '#{params[:adword_present]}' ILIKE ANY (right_adwords_url)")
  	end
  	respond_to do |format|
  		format.html
  		format.any(:xml, :json) { render request.format.to_sym => @reports }
  	end
  end

  def show
  	@report = Report.find(params[:id])
  	respond_to do |format|
  		format.html
  		format.any(:xml, :json) { render request.format.to_sym => @report }
  	end
  end

  def new
  	@report = current_user.reports.new
  end

  def create
  	keywords = open_spreadsheet(params[:file])

  	unless keywords.nil?
  		keywords = keywords.row(1)
  		keywords.each do |keyword|
  		  reformat_keyword = keyword.gsub(" ","+")
          doc = Nokogiri::HTML(open('http://www.google.com/search?q='+reformat_keyword))
          report = current_user.reports.new
          report.keyword = keyword

          # Top adwords
          top_array = []
		  doc.css('div#tads ol li cite').each do |link|
		  	top_array << link.text
		  end
		  report.top_adwords_url  = top_array

		  # Right adwords
		  right_array = []
		  doc.css('div#mbEnd ol li cite').each do |link|
		  	right_array << link.text
		  end
		  report.right_adwords_url  = right_array

		  # Non adwords
		  non_adwords_array = []
		  doc.css('div#ires ol li cite').each do |link|
		  	non_adwords_array << link.text
		  end
		  report.non_adwords_url  = non_adwords_array

		  # Result stats
		  report.total_results = doc.css('div#resultStats').text

		  #  Page cache
		  report.page_cache = PGconn.escape_bytea(doc.to_s)

		  report.save
  		end
  	end

	respond_to do |format|
		format.html {redirect_to api_v1_reports_index_url}
  		# format.any(:xml, :json) { render request.format.to_sym => @people }
  	end
  end

  private
   # To check uploaded file is CSV or not
  def open_spreadsheet(file)
    case File.extname(file.original_filename)
      when ".csv" then Roo::CSV.new(file.path)
      else raise "Unknown file type: #{file.original_filename}"
    end
  end

  def report_params
    params.require(:report).permit(:keyword, :top_adwords_url, :right_adwords_url, :non_adwords_url, :total_results, :page_cache)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # CUSTOM EXCEPTION HANDLING
  rescue_from StandardError do |e|
    error(e)
  end

  def routing_error
    raise ActionController::RoutingError.new(params[:path])
  end

  protected

  def error(e)
    #render :template => "#{Rails::root}/public/404.html"
    if env["ORIGINAL_FULLPATH"] =~ /^\/api/
    error_info = {
      :error => "internal-server-error",
      :exception => "#{e.class.name} : #{e.message}",
    }
    error_info[:trace] = e.backtrace[0,10] if Rails.env.development?
    render :json => error_info.to_json, :status => 500
    else
      #render :text => "500 Internal Server Error", :status => 500 # You can render your own template here
      raise e
    end
  end

end

app/controllers/home_controller.rb
# Home controller
class HomeController < ApplicationController
end

app/controllers/reports_controller.rb
require 'nokogiri'
require 'open-uri'

# Controller for Reports
class ReportsController < ApplicationController
	before_filter :authenticate_user!
	#  List of reports
  def index
  	@reports = current_user.reports
  	if !params[:adword_present].nil?
  		@reports = @reports.where("'%#{params[:adword_present]}%' ~~*^ ANY (top_adwords_url) OR '%#{params[:adword_present]}%' ~~*^ ANY (right_adwords_url)")
  	end

  	if !params[:url_present].nil?
  		@reports = @reports.where("'#{params[:url_present]}' ~~*^ ANY (non_adwords_url)")
  	end
  end

  # Show report
  def show
  	@report = Report.find(params[:id])
  end

  # New report
  def new
  	@report = current_user.reports.new
  end

  # Create report
  def create
  	keywords = open_spreadsheet(params[:file])

  	unless keywords.nil?
  		keywords = keywords.row(1)
  		begin
  			keywords.each do |keyword|
  		  reformat_keyword = keyword.gsub(" ","+")
          doc = Nokogiri::HTML(open('http://www.google.com/search?q='+reformat_keyword))
          report = current_user.reports.new
          report.keyword = keyword

          # Top adwords
          top_array = []
				  doc.css('div#tads ol li cite').each do |link|
				  	top_array << link.text
				  end
				  report.top_adwords_url  = top_array

				  # Right adwords
				  right_array = []
				  doc.css('div#mbEnd ol li cite').each do |link|
				  	right_array << link.text
				  end
				  report.right_adwords_url  = right_array

				  # Non adwords
				  non_adwords_array = []
				  doc.css('div#ires ol li cite').each do |link|
				  	non_adwords_array << link.text
				  end
				  report.non_adwords_url  = non_adwords_array

				  # Result stats
				  report.total_results = doc.css('div#resultStats').text

				  #  Page cache
				  report.page_cache = PGconn.escape_bytea(doc.to_s)

				  report.save
  			end
  		rescue Exception => exc
  			logger.error("Message for the log file #{exc.message}")
  			flash[:notice] = "Unable to process keywords"
  			redirect_to reports_url
  		end
  	end
  	@reports = current_user.reports
  	redirect_to reports_url, notice: "Reports are successfully created"
  end

  private
   # To check uploaded file is CSV or not
  def open_spreadsheet(file)
    case File.extname(file.original_filename)
      when ".csv" then Roo::CSV.new(file.path)
      else raise "Unknown file type: #{file.original_filename}"
    end
  end

  # Only allow a trusted parameter "white list" through.
  def report_params
    params.require(:report).permit(:keyword, :top_adwords_url, :right_adwords_url, :non_adwords_url, :total_results, :page_cache)
  end
end

app/helpers/api/v1/reports_helper.rb
module Api::V1::ReportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="jumbotron" align="center">
	<h2>Welcome to google search reporting tool</h2>
	<img src="assets/google-search.jpg">
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoogleScraper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to root_path,class: "navbar-brand" do %>
      	<i class="glyphicon glyphicon-home"></i> Home
      <% end %>
    </div>
    <div>
      <ul class="nav navbar-nav">
      	<% if user_signed_in? %>
      		<li><%= link_to "Google Report", reports_path %></li>
      	<% end %>
      </ul>
      <ul class="nav navbar-nav pull-right">
      	<% if user_signed_in? %>
      		<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
      	<% else %>
	      	<li><%= link_to "Sign in", new_user_session_path %></li>
	      	<li><%= link_to "Sign up", new_user_registration_path %></li>
      	<% end %>
      </ul>
    </div>
  </div>
</nav>
 <%= render partial: 'layouts/flash_messages' %>
 <div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-12">
          <%= yield %>
        </div>
      </div>
    </div>

</body>
</html>

app/views/reports/index.html.erb
<div class="page-header" style="margin-bottom: 70px;">
	<h1>Searched Reports</h1>
</div>

<div class="well">
	<div class="row">
		<div class="col-xs-4" >
			<%= form_tag reports_path, {method: :get , class: 'form-class'}  do %>
				<%= label_tag 'Search Adwords' %><br/>
				<%=text_field_tag 'adword_present', nil, placeholder:'Word present in Adwords'%>
				<%= submit_tag("Get", class: "btn btn-success btn-sm") %>
			<% end %>
		</div>
		<div class="col-xs-4">
			<%= form_tag reports_path, {method: :get , class: 'form-class'}  do %>
				<%= label_tag 'Url in Seo' %><br/>
				<%=text_field_tag 'url_present', nil, placeholder:'Enter Url'%>
				<%= submit_tag("Get", class: "btn btn-success btn-sm") %>
			<% end %>
		</div>
		<div class="col-xs-4 pad-top" align="center">
			<%= link_to "New Report", new_report_path, class: "btn btn-success btn-sm" %>
		</div>
	</div>
</div>

<div class="jumbotron">
	<table class="table">
		<caption>Records: <%=@reports.count%> <%=link_to "Reset", reports_path, class: "btn btn-sm btn-default pull-right" %></caption>
	   <thead>
	      <tr>
	         <th>Keyword</th>
	         <th>Top Adwords</th>
	         <th>Right Adwords</th>
	         <th>Total Adwords</th>
	         <th>Non Adwords</th>
	         <th>Total Results</th>
	         <th>Total Links</th>
	      </tr>
	   </thead>
	   <tbody>
		<% @reports.each do |report| %>
	  	  <tr>
	        <td><%=link_to report.keyword, report_path(report.id) %></td>
	        <td><%=report.top_adwords_number%></td>
	        <td><%=report.right_adwords_number%></td>
	        <td><%=report.total_adwords_number%></td>
	        <td><%=report.non_adwords_number%></td>
	        <td><%=report.total_results%></td>
	        <td><%=report.total_links%></td>
	      </tr>
		<%end%>
	   </tbody>
	</table>
</div>

app/views/reports/new.html.erb
	<div class="row">
		<div class="col-xs-9 pad-center" >
			<div class="well">
				<%= form_tag reports_path, {class: 'form-class', multipart: true}  do %>
					<label for="file">Select CSV to Upload</label>
					<%= file_field_tag "file" %>
					<br/>
					<%= submit_tag("Save", class: "btn btn-success btn-sm") %>
					<%=link_to "Cancel", reports_path, class: "btn btn-sm btn-default" %>
				<% end %>
			</div>
		</div>
	</div>

app/views/reports/show.html.erb
	<div class="row">
		<div class="col-xs-9 pad-center" >
			<div class="well">
				<h1><%= @report.keyword%></h1>
				<div class="span">
					<label>Total of search Results</label>
					<p>
						<%if !@report.total_results.blank?%>
							<%=@report.total_results%>
						<%else%>
							<%="N/A"%>
						<%end%>
					</p>
				</div>
				<div class="span">
					<label>Top Adwords Url</label>
					<p>
						<%if !@report.top_adwords_url.empty?%>
							<%=@report.top_adwords_url%>
						<%else%>
							<%="N/A"%>
						<%end%>
					</p>
				</div>
				<div class="span">
					<label>Right Adwords Url</label>
					<p>
						<%if !@report.right_adwords_url.empty?%>
							<%=@report.right_adwords_url%>
						<%else%>
							<%="N/A"%>
						<%end%>
					</p>
				</div>
				<div class="span">
					<label>Non Adwords Url</label>
					<p>
						<%if !@report.non_adwords_url.empty?%>
							<%=@report.non_adwords_url%>
						<%else%>
							<%="N/A"%>
						<%end%>
					</p>
				</div>
				<%=link_to "Back", reports_path, class: "btn btn-sm btn-success" %>
			</div>
		</div>
	</div>